import 'package:flutter/material.dart';

import '../model/product_model.dart';

class mlistprovider extends ChangeNotifier {
  List<ProductModel> megaproducts = [
    ProductModel(
        flashButton: 'assets/images/habag.png',
        text: 'Gucci Selma Bag',
        text1: '15000',
        price: 12000,
        text3: '20% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
    ProductModel(
        flashButton: 'assets/images/stylish.png',
        text: 'Goldstar A100',
        text1: "19000",
        price: 14000,
        text3: '23% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
    ProductModel(
        flashButton: 'assets/images/handdbag.png',
        text: 'Bello handbag',
        text1: '12000',
        price: 8000,
        text3: '30% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
    ProductModel(
        flashButton: 'assets/images/watch.png',
        text: 'Nike series 5',
        text1: '4000',
        price: 3000,
        text3: '12% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
    ProductModel(
        flashButton: 'assets/images/habag.png',
        text: 'Gucci Selma Bag',
        text1: '15000',
        price: 12000,
        text3: '20% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
    ProductModel(
        flashButton: 'assets/images/stylish.png',
        text: 'Goldstar A100',
        text1: "19000",
        price: 14000,
        text3: '23% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
    ProductModel(
        flashButton: 'assets/images/handdbag.png',
        text: 'Bello handbag',
        text1: '12000',
        price: 8000,
        text3: '30% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
    ProductModel(
        flashButton: 'assets/images/watch.png',
        text: 'Nike series 5',
        text1: '4000',
        price: 3000,
        text3: '12% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
    ProductModel(
        flashButton: 'assets/images/habag.png',
        text: 'Gucci Selma Bag',
        text1: '15000',
        price: 12000,
        text3: '20% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
    ProductModel(
        flashButton: 'assets/images/stylish.png',
        text: 'Goldstar A100',
        text1: "19000",
        price: 14000,
        text3: '23% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
    ProductModel(
        flashButton: 'assets/images/handdbag.png',
        text: 'Bello handbag',
        text1: '12000',
        price: 8000,
        text3: '30% off',
        // touched: () {},
        desc: 'we',
        isFav: false),
  ];
}
